name: Publish Docker images

on:
  create:
    tags: ['v*']
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  push_builder:
    name: Ploi
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract Builder meta
        id: builder-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.builder-meta.outputs.tags }}
          labels: ${{ steps.builder-meta.outputs.labels }}
          build-args: |
            SCOPE=builder
